import { createElement } from "react";
import {
  BookOpen,
  Bot,
  Brain,
  Clock,
  Database,
  Flame,
  Folder,
  GitBranch,
  Globe,
  Image as ImageIcon,
  ListTree,
  MousePointerClick,
  Search,
  Sparkles,
  Telescope,
  TestTube,
} from "lucide-react";
import {
  SiAirtable,
  SiAtlassian,
  SiBrave,
  SiClickhouse,
  SiCloudflare,
  SiElevenlabs,
  SiFigma,
  SiGithub,
  SiGitlab,
  SiGooglemaps,
  SiHuggingface,
  SiKagi,
  SiLinear,
  SiMattermost,
  SiMongodb,
  SiNotion,
  SiObsidian,
  SiPaypal,
  SiPostgresql,
  SiPuppeteer,
  SiRedis,
  SiResend,
  SiSentry,
  SiSlack,
  SiSqlite,
  SiStripe,
  SiSupabase,
} from "react-icons/si";

const LOGO = "h-5 w-5";

const simpleIcon = (Icon) => createElement(Icon, { className: LOGO });
const lucideIcon = (Icon) =>
  createElement(Icon, { className: LOGO, strokeWidth: 2.25 });

export const MCP_FALLBACK_LOGO = lucideIcon(Bot);

export const MCP_LOGOS = {
  github: simpleIcon(SiGithub),
  slack: simpleIcon(SiSlack),
  tavily: createElement(Search, { className: LOGO, strokeWidth: 2.5 }),
  linear: simpleIcon(SiLinear),
  notion: simpleIcon(SiNotion),
  atlassian: simpleIcon(SiAtlassian),
  sentry: simpleIcon(SiSentry),
  stripe: simpleIcon(SiStripe),
  paypal: simpleIcon(SiPaypal),
  "cloudflare-docs": simpleIcon(SiCloudflare),
  "cloudflare-bindings": simpleIcon(SiCloudflare),
  "cloudflare-observability": simpleIcon(SiCloudflare),
  huggingface: simpleIcon(SiHuggingface),
  deepwiki: simpleIcon(BookOpen),
  gitlab: simpleIcon(SiGitlab),
  git: lucideIcon(GitBranch),
  "brave-search": simpleIcon(SiBrave),
  exa: lucideIcon(Telescope),
  firecrawl: lucideIcon(Flame),
  apify: lucideIcon(Bot),
  fetch: lucideIcon(Globe),
  "browser-mcp": lucideIcon(MousePointerClick),
  playwright: lucideIcon(TestTube),
  puppeteer: simpleIcon(SiPuppeteer),
  "google-maps": simpleIcon(SiGooglemaps),
  postgres: simpleIcon(SiPostgresql),
  supabase: simpleIcon(SiSupabase),
  neon: lucideIcon(Database),
  mongodb: simpleIcon(SiMongodb),
  redis: simpleIcon(SiRedis),
  sqlite: simpleIcon(SiSqlite),
  filesystem: lucideIcon(Folder),
  memory: lucideIcon(Brain),
  "sequential-thinking": lucideIcon(ListTree),
  time: lucideIcon(Clock),
  everart: lucideIcon(ImageIcon),
  everything: lucideIcon(Sparkles),
  "aws-kb": lucideIcon(BookOpen),
  figma: simpleIcon(SiFigma),
  airtable: simpleIcon(SiAirtable),
  obsidian: simpleIcon(SiObsidian),
  elevenlabs: simpleIcon(SiElevenlabs),
  resend: simpleIcon(SiResend),
  "cloudflare-builds": simpleIcon(SiCloudflare),
  "cloudflare-browser-rendering": simpleIcon(SiCloudflare),
  kagi: simpleIcon(SiKagi),
  clickhouse: simpleIcon(SiClickhouse),
  mattermost: simpleIcon(SiMattermost),
};

export const MCP_LOGO_IDS = new Set(Object.keys(MCP_LOGOS));
